/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        kotlin("jvm") version "1.9.25"
        kotlin("plugin.spring") version "1.9.25"
        id("org.springframework.boot") version "3.2.5"
        id("io.spring.dependency-management") version "1.1.5"
    }
}

rootProject.name = "faculty_day"
include("lesson1")
include("lesson2")
include("lesson3")
//include("lesson4")
//include("lesson5")
//include("lesson6")
include("lesson7")
//include("simple")
include("lesson8")
//include("lesson9")
include("lesson10")
include("lesson11")
include("lesson12")