/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        kotlin("jvm") version "1.9.25"
        kotlin("plugin.spring") version "1.9.25"
        id("org.springframework.boot") version "3.5.9"
        id("io.spring.dependency-management") version "1.1.7"
        id("org.openapi.generator") version "7.3.0"
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "faculty_day"
include("lesson2")
include("lesson3")
//include("lesson4")
//include("lesson5")
//include("lesson6")
include("lesson7")
//include("simple")
include("lesson8")
//include("lesson9")
include("lesson10")
include("lesson11")
include("lesson12")
include("lesson13")
include("lesson14")